### ISSUE TITLE
Is batch_size here right?

### ISSUE THREAD

**Issue by Renovamen** [teddykoker/tinyloader#2]
Hey @teddykoker, thanks for your nice work! But I guess maybe here:

https://github.com/teddykoker/tinyloader/blob/cb62482ec2d23d51757d2f50c8159f124499662b/dataloader.py#L30

should be:

```python
batch_size = min(len(self.dataset) - self.index, self.batch_size)
```

And thanks for your code again.

**Comment by teddykoker** [comment]
Great catch! Thanks for the issue :)
